# Generated by Django 4.2.5 on 2023-09-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_video_uservideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservideo',
            name='password',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uservideo',
            name='username',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
