# Generated by Django 4.2.5 on 2023-09-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_uservideo_password_uservideo_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='uservideo',
            name='password',
        ),
        migrations.RemoveField(
            model_name='uservideo',
            name='username',
        ),
    ]
