# Generated by Django 4.2.5 on 2023-09-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_testdateandtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdateandtime',
            name='created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='testdateandtime',
            name='time',
            field=models.DateField(null=True),
        ),
    ]
