# Generated by Django 4.2.5 on 2023-09-12 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_testdateandtime_created_testdateandtime_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdateandtime',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
